kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "aca-py-agent-toolbox"
spec:
  runPolicy: "Serial"
  source:
    type: Docker
    dockerfile: "FROM image-registry.openshift-image-registry.svc:5000/av-images/aca-py-agent:latest\nRUN pip3 install --no-cache-dir -e 'git+https://github.com/dbluhm/aries-acapy-plugin-toolbox.git@update/aca-py-0.6.0rc0#egg=aries-acapy-plugin-toolbox'"
  strategy:
    type: Docker
  output:
    to:
      kind: "ImageStreamTag"
      namespace: "av-images"
      name: "aca-py-agent-toolbox:latest"
