kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "aca-py-agent"
spec:
  runPolicy: "Serial"
  source:
    type: Git
    git:
      uri: "https://github.com/brianorwhatever/aries-cloudagent-python"
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: docker/Dockerfile.run
  output:
    to:
      kind: "ImageStreamTag"
      namespace: "av-images"
      name: "aca-py-agent:latest"
