kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "av1-apis"
spec:
  runPolicy: "Serial"
  source:
    type: Git
    git:
      uri: "git@github.com:aviarytech/av1-apis.git"
    sourceSecret:
      name: "av1-apis-deploy-key"
      namespace: av1
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: "ImageStreamTag"
      namespace: "av-images"
      name: "av1-apis:latest"
