kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: "av1-apis"
spec:
  runPolicy: "Serial"
  triggers:
    - type: "GitHub"
      github:
        secretReference:
          name: "github-webhook-secret"
  source:
    type: Git
    git:
      uri: "git@github.com:aviarytech/av1-apis.git"
    sourceSecret:
      name: "av1-apis-deploy-key"
      namespace: av1
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: "av-images"
        name: node:latest
  output:
    to:
      kind: "ImageStreamTag"
      namespace: "av-images"
      name: "av1-apis:latest"
