kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: node
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: 'centos/nodejs-12-centos7:latest'
      generation: 1
      importPolicy: {}
      referencePolicy:
        type: Source
