kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: postgres
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest
