kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: postgres
spec:
  lookupPolicy:
    local: true
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.redhat.io/rhel8/postgresql-12:latest
